run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - gofmt
    - vet
    - gosimple
    - unconvert
    - ineffassign
    - misspell
    - bodyclose
    - rowserrcheck
    - sqlclosecheck
