// Copyright (c) 2022 The Decred developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package gitbe

const (
	// Journal filenames
	CommentsJournalFilename = "comments.journal"
	BallotJournalFilename   = "ballot.journal"

	// Journal actions
	JournalActionAdd     = "add"     // Add entry
	JournalActionDel     = "del"     // Delete entry
	JournalActionAddLike = "addlike" // Add comment like
)

// JournalAction prefixes and determines what the next structure is in the JSON
// journal.
//
// Version is used to determine what version of the comment journal structure
// follows.
type JournalAction struct {
	Version string `json:"version"`
	Action  string `json:"action"`
}

// Comment is the journal entry for a JournalActionAdd action.
//
// Signature is the client signature of the Token+ParentID+Comment.
//
// Receipt is the server signature of the client signature.
type Comment struct {
	Token     string `json:"token"`     // Censorship token
	ParentID  string `json:"parentid"`  // Parent comment ID
	Comment   string `json:"comment"`   // Comment text
	Signature string `json:"signature"` // Client signature
	PublicKey string `json:"publickey"` // Client public key
	CommentID string `json:"commentid"` // Comment ID
	Receipt   string `json:"receipt"`   // Server receipt
	Timestamp int64  `json:"timestamp"` // Received UNIX timestamp

	// The following fields exist but will always be their zero value. This
	// is the result of the initial implementation including these fields in
	// error.
	TotalVotes  uint64 `json:"totalvotes"`  // Total number of up/down votes
	ResultVotes int64  `json:"resultvotes"` // Vote score
	Censored    bool   `json:"censored"`    // Has this comment been censored
}

// CensorComment is a journal entry for a JournalActionDel action.
//
// Signature is the admin signature of the Token+CommentID+Reason.
//
// Receipt is the server signature of the admin signature.
type CensorComment struct {
	Token     string `json:"token"`     // Censorship token
	CommentID string `json:"commentid"` // Comment ID
	Reason    string `json:"reason"`    // Reason comment was censored
	Signature string `json:"signature"` // Admin signature
	PublicKey string `json:"publickey"` // Admin public key

	// Generated by the server
	Receipt   string `json:"receipt"`   // Server receipt
	Timestamp int64  `json:"timestamp"` // Received UNIX timestamp
}

// LikeComment is the journal entry for a JournalActionAddLike action.
//
// Signature is the client signature of the Token+CommentID+Action.
//
// Receipt is the server signature of the client signature.
type LikeComment struct {
	Token     string `json:"token"`     // Censorship token
	CommentID string `json:"commentid"` // Comment ID
	Action    string `json:"action"`    // Up or downvote (1, -1)
	Signature string `json:"signature"` // Client signature
	PublicKey string `json:"publickey"` // Client public key

	// Generated by the server
	Receipt   string `json:"receipt"`   // Server receipt
	Timestamp int64  `json:"timestamp"` // Received UNIX timestamp
}

// CastVoteJournal represents a ballot journal entry.
type CastVoteJournal struct {
	CastVote CastVote `json:"castvote"`
	Receipt  string   `json:"receipt"` // Server receipt
}

// CastVote is a signed vote.
//
// Signature is the signature of the Token+Ticket+VoteBit.
type CastVote struct {
	Token     string `json:"token"`
	Ticket    string `json:"ticket"`
	VoteBit   string `json:"votebit"`
	Signature string `json:"signature"`
}
